# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: environment_name
  type: string
- name: environment_file
  type: string

steps:
  - task: AzureCLI@2
    displayName: Register Azure ML environment 
    continueOnError: true
    inputs: 
      azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level 
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: |
        az ml environment create --name ${{ parameters.environment_name }} --file ${{ parameters.environment_file }}
